:bug: Fix import missing prisma/utils/csv-extract.ts:184:5 - error TS2322: Type '{ structureDnaCode: any; date: Date; ETP: number; tauxEncadrement: number; coutJournalier: number; dotationDemandee: number; dotationAccordee: number; totalProduits: number; totalCharges: number; ... 9 more ...; commentaire: any; }[]' is not assignable to type 'Omit<{ date: Date; ETP: number; tauxEncadrement: number; coutJournalier: number; dotationDemandee: number; dotationAccordee: number | null; totalProduits: number | null; totalCharges: number | null; ... 12 more ...; structureDnaCode: string; }, "id">[]'.
  Property 'totalChargesProposees' is missing in type '{ structureDnaCode: any; date: Date; ETP: number; tauxEncadrement: number; coutJournalier: number; dotationDemandee: number; dotationAccordee: number; totalProduits: number; totalCharges: number; ... 9 more ...; commentaire: any; }' but required in type 'Omit<{ date: Date; ETP: number; tauxEncadrement: number; coutJournalier: number; dotationDemandee: number; dotationAccordee: number | null; totalProduits: number | null; totalCharges: number | null; ... 12 more ...; structureDnaCode: string; }, "id">'.