Jerem/form finalisation 3 (#310)
* WIP: step 01 with almost validation

* :bug: Fix dates issues

* :sparkles: Refac + Finalisation form 1 + Finalisation form 2

* Jerem/form finalisation 2 (#295)

* :construction: WIP my branch like a boss

* :art: Fix linter errs

* :art: Linter again

* :rotating_light: Fix csv extract err

* :wastebasket: Remove import script

* :poop: Cleanup verbose comments

* :art: A bit of code cleanup

* :art: Code review

* :art: Compile err fix

* :art: Code review

* :poop: Ooopsy

* :art: Fix compiler errs

* :sparkles: WIP form finalisation budget screen from hell

* :bug: Fix import missing prisma/utils/csv-extract.ts:184:5 - error TS2322: Type '{ structureDnaCode: any; date: Date; ETP: number; tauxEncadrement: number; coutJournalier: number; dotationDemandee: number; dotationAccordee: number; totalProduits: number; totalCharges: number; ... 9 more ...; commentaire: any; }[]' is not assignable to type 'Omit<{ date: Date; ETP: number; tauxEncadrement: number; coutJournalier: number; dotationDemandee: number; dotationAccordee: number | null; totalProduits: number | null; totalCharges: number | null; ... 12 more ...; structureDnaCode: string; }, "id">[]'.

  Property 'totalChargesProposees' is missing in type '{ structureDnaCode: any; date: Date; ETP: number; tauxEncadrement: number; coutJournalier: number; dotationDemandee: number; dotationAccordee: number; totalProduits: number; totalCharges: number; ... 9 more ...; commentaire: any; }' but required in type 'Omit<{ date: Date; ETP: number; tauxEncadrement: number; coutJournalier: number; dotationDemandee: number; dotationAccordee: number | null; totalProduits: number | null; totalCharges: number | null; ... 12 more ...; structureDnaCode: string; }, "id">'.

* :construction: WIP: Finance form + send data to backend

* :art: Fix TS error ?

* :construction: Fix ts error ?

* :construction: WIP: qualite files form

* :goal_net: Fix compiler err